"""v0.1

Revision ID: 787738fb2362
Revises: f6778600730b
Create Date: 2019-06-22 17:57:41.370758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787738fb2362'
down_revision = 'f6778600730b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'files', ['id'])
    op.create_unique_constraint(None, 'incedents', ['id'])
    op.create_unique_constraint(None, 'incedents_points', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'name')
    op.drop_column('users', 'comfirmed')
    op.drop_column('users', 'comfirm_code')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('comfirm_code', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('comfirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'incedents_points', type_='unique')
    op.drop_constraint(None, 'incedents', type_='unique')
    op.drop_constraint(None, 'files', type_='unique')
    # ### end Alembic commands ###
